### ISSUE TITLE
i had run this project and found an RuntimeError: shape '[32, 48, 16]' is invalid for input of size 22020096.

### ISSUE THREAD

**Issue by LuluQin766** [JiYuanFeng/MCTrans#16]
I use the pannuke dataset. But I found an error.
`
Traceback (most recent call last):
  File "tools/train.py", line 138, in <module>
    main()
  File "tools/train.py", line 135, in main
    SegPipline(cfg, distributed, not args.no_validate).run()
  File "/home/aMI_projects/MCTrans-master/mctrans/pipline/segpipline.py", line 99, in run
    self.runner.run(self.data_loaders, self.cfg.workflow, self.cfg.max_epochs)
  File "/home/anaconda3/envs/mctrans/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/anaconda3/envs/mctrans/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "/home/anaconda3/envs/mctrans/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 30, in run_iter
    **kwargs)
  File "/home/anaconda3/envs/mctrans/lib/python3.7/site-packages/mmcv/parallel/data_parallel.py", line 75, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/aMI_projects/MCTrans-master/mctrans/models/segmentors/base.py", line 152, in train_step
    losses = self(**data_batch)
  File "/home/anaconda3/envs/mctrans/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/anaconda3/envs/mctrans/lib/python3.7/site-packages/mmcv/runner/fp16_utils.py", line 109, in new_func
    return old_func(*args, **kwargs)
  File "/home/aMI_projects/MCTrans-master/mctrans/models/segmentors/base.py", line 122, in forward
    return self.forward_train(img, img_metas, **kwargs)
  File "/home/aMI_projects/MCTrans-master/mctrans/models/segmentors/encoder_decoder.py", line 92, in forward_train
    loss_aux = self._auxiliary_head_forward(x, seg_label, return_loss=True)
  File "/home/aMI_projects/MCTrans-master/mctrans/models/segmentors/encoder_decoder.py", line 81, in _auxili           ary_head_forward
    return self.aux_head.forward_train(x, seg_label)
  File "/home/aMI_projects/MCTrans-master/mctrans/models/heads/mctrans_aux_head.py", line 51, in forward_train
    outputs = self.ca(inputs_flatten)
  File "/home/anaconda3/envs/mctrans/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/aMI_projects/MCTrans-master/mctrans/models/trans/transformer.py", line 149, in forward
    query = layer(query, src)
  File "/home/anaconda3/envs/mctrans/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/aMI_projects/MCTrans-master/mctrans/models/trans/transformer.py", line 124, in forward
    tgt2 = self.cross_attn(tgt, src, src)[0]
  File "/home/anaconda3/envs/mctrans/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/anaconda3/envs/mctrans/lib/python3.7/site-packages/torch/nn/modules/activation.py", line 1045, in forward
    attn_mask=attn_mask, average_attn_weights=average_attn_weights)
  File "/home/anaconda3/envs/mctrans/lib/python3.7/site-packages/torch/nn/functional.py", line 5301, in multi_head_attention_forward
    k = k.contiguous().view(k.shape[0], bsz * num_heads, head_dim).transpose(0, 1)
RuntimeError: shape '[32, 48, 16]' is invalid for input of size 22020096
`

**Comment by LuluQin766** [comment]
I found the error from the code in the /mctrans/models/trans/transformer.py
```
class CALayer(nn.Module):
def forward(self, tgt, src):
q = k = tgt
tgt2 = self.self_attn(q.transpose(0, 1), k.transpose(0, 1), tgt.transpose(0, 1))[0].transpose(0, 1)
tgt = tgt + self.dropout2(tgt2)
tgt = self.norm2(tgt)

  tgt2 = self.cross_attn(tgt, src, src)[0] # error from this line.
  tgt = tgt + self.dropout1(tgt2)
  tgt = self.norm1(tgt)
  # ffn
  tgt = self.forward_ffn(tgt)
  return tgt
```

**Comment by LuluQin766** [comment]
so I modified this code into ...
```
class CALayer(nn.Module):
def forward(self, tgt, src):
# self attention
q = k = tgt
tgt2 = self.self_attn(q.transpose(0, 1), k.transpose(0, 1), tgt.transpose(0, 1))[0].transpose(0, 1)
tgt = tgt + self.dropout2(tgt2)
tgt = self.norm2(tgt)

  # cross attention
  tgt2 = self.cross_attn(tgt.transpose(0, 1), src.transpose(0, 1), src.transpose(0, 1))[0].transpose(0, 1)
  tgt = tgt + self.dropout1(tgt2)
  tgt = self.norm1(tgt)
  # ffn
  tgt = self.forward_ffn(tgt)
  return tgt
```

**Comment by LuluQin766** [comment]
It can run. But I'm not sure if this is right. 
Also, I found something wrong with the results.
![image](https://user-images.githubusercontent.com/45515462/158600201-170c6ca5-3462-4ca4-a53a-a6d9db126ee5.png)

**Comment by JiYuanFeng** [comment]
Hi, Can you provide the version information of your installed monai? Can you install monai == 0.5.3 and try again with the default code.

**Comment by LuluQin766** [comment]
Thanks for your answer. The monai version of my environment is 0.8.1. After I install monai == 0.5.3, it is work. Thanks again.
![image](https://user-images.githubusercontent.com/45515462/158953577-e9ae17f6-1bea-4960-8bdc-b83433716e6e.png)

**Comment by JiYuanFeng** [comment]
Nice！

**Comment by zqing10** [comment]
hello!Can you tell me after the operation of ‘transpose(0,1)’ is the final average F1 68.9 ？ same to paper？ My F1 metric only is 67.13. 
![QQ图片20220417101219](https://user-images.githubusercontent.com/62885530/163697354-a5c3ba67-1f05-456e-a8bd-ca3931e49e35.png)

**Comment by edautumn** [comment]
> 感谢您的回答。我的环境的monai版本是0.8.1。在我安装了 monai == 0.5.3 之后，它就可以工作了。再次感谢。 ![图片](https://user-images.githubusercontent.com/45515462/158953577-e9ae17f6-1bea-4960-8bdc-b83433716e6e.png)

想要求一下你的MCTran文件，我目前无法运行这个模型
