### ISSUE TITLE
使用其他数据集出现的问题 AttributeError: 'ConfigDict' object has no attribute 'log_level'等等

### ISSUE THREAD

**Issue by haomayang1126** [JiYuanFeng/MCTrans#20]
我是用自己的数据集，使用模型mctrans_vgg32_d5.py，
显示：Traceback (most recent call last):
  File "G:/codelearn/papercode329/3MCTrans-master/tools/train.py", line 128, in <module>
    main()
  File "G:/codelearn/papercode329/3MCTrans-master/tools/train.py", line 103, in main
    print(cfg.log_level)
  File "g:\pythonproject\swin-zhenghe\mmcv-1.3.1\mmcv\utils\config.py", line 425, in __getattr__
    return getattr(self._cfg_dict, name)
  File "g:\pythonproject\swin-zhenghe\mmcv-1.3.1\mmcv\utils\config.py", line 44, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'log_level'
请问有人知道什么问题吗，感谢

手动将log level设置为0

出现错误：
AttributeError: 'ConfigDict' object has no attribute 'data'

我怀疑是配置文件没弄好，有大哥知道嘛

**Comment by JiYuanFeng** [comment]
please follow the configuration structure (https://github.com/JiYuanFeng/MCTrans/blob/master/configs/pannuke-vgg32/mctrans_vgg32_d5_256x256_400ep_pannuke.py) to add other configurations such as dataset info/schedule
