### ISSUE TITLE
DLL load failed

### ISSUE THREAD

**Issue by jscodecode** [JiYuanFeng/MCTrans#24]
How can I solve this problems？ Thanks you very much！！！

`Traceback (most recent call last):
  File "Z:\py_item\7_MCTrans-master\MCTrans-master\tools\train.py", line 14, in <module>
    from mctrans.pipline import SegPipline
  File "Z:\py_item\7_MCTrans-master\MCTrans-master\mctrans\pipline\__init__.py", line 1, in <module>
    from .segpipline import SegPipline
  File "Z:\py_item\7_MCTrans-master\MCTrans-master\mctrans\pipline\segpipline.py", line 7, in <module>
    from mctrans.models import build_model
  File "Z:\py_item\7_MCTrans-master\MCTrans-master\mctrans\models\__init__.py", line 1, in <module>
    from .centers import *
  File "Z:\py_item\7_MCTrans-master\MCTrans-master\mctrans\models\centers\__init__.py", line 1, in <module>
    from .mctrans import MCTrans
  File "Z:\py_item\7_MCTrans-master\MCTrans-master\mctrans\models\centers\mctrans.py", line 8, in <module>
    from ..ops.modules import MSDeformAttn
  File "Z:\py_item\7_MCTrans-master\MCTrans-master\mctrans\models\ops\modules\__init__.py", line 9, in <module>
    from .ms_deform_attn import MSDeformAttn
  File "Z:\py_item\7_MCTrans-master\MCTrans-master\mctrans\models\ops\modules\ms_deform_attn.py", line 21, in <module>
    from ..functions import MSDeformAttnFunction
  File "Z:\py_item\7_MCTrans-master\MCTrans-master\mctrans\models\ops\functions\__init__.py", line 9, in <module>
    from .ms_deform_attn_func import MSDeformAttnFunction
  File "Z:\py_item\7_MCTrans-master\MCTrans-master\mctrans\models\ops\functions\ms_deform_attn_func.py", line 18, in <module>
    import MultiScaleDeformableAttention as MSDA
ImportError: DLL load failed: 找不到指定的模块。`

**Comment by JiYuanFeng** [comment]
hi, please see https://github.com/open-mmlab/mmcv/issues/1975
